name: acorn.lojistiks::lang.models.productinstancetransfer.label
form: $/acorn/lojistiks/models/productinstancetransfer/fields.yaml
modelClass: Acorn\Lojistiks\Models\ProductInstanceTransfer
defaultRedirect: acorn/lojistiks/productinstancetransfer
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/productinstancetransfer/update/:id
  redirectClose: acorn/lojistiks/productinstancetransfer
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/productinstancetransfer
  redirectClose: acorn/lojistiks/productinstancetransfer
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
