name: acornassociated.lojistiks::lang.models.productinstancetransfer.label
form: $/acornassociated/lojistiks/models/productinstancetransfer/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\ProductInstanceTransfer
defaultRedirect: acornassociated/lojistiks/productinstancetransfer
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/productinstancetransfer/update/:id
  redirectClose: acornassociated/lojistiks/productinstancetransfer
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/productinstancetransfer
  redirectClose: acornassociated/lojistiks/productinstancetransfer
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
