# Created By acorn-create-system v1.0
lojistiks_product_categories_product_category_type:
  label: acornassociated.lojistiks::lang.models.productcategory.label_plural
  view:
    list: $/acornassociated/lojistiks/models/productcategory/columns.yaml
    toolbarButtons: create|delete
    showCheckboxes: true
    recordsPerPage: 10
  manage:
    form: $/acornassociated/lojistiks/models/productcategory/fields.yaml
    recordsPerPage: 10
