name: acorn.lojistiks::lang.models.measurementunit.label
form: $/acorn/lojistiks/models/measurementunit/fields.yaml
modelClass: Acorn\Lojistiks\Models\MeasurementUnit
defaultRedirect: acorn/lojistiks/measurementunits
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/measurementunits/update/:id
  redirectClose: acorn/lojistiks/measurementunits
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/measurementunits
  redirectClose: acorn/lojistiks/measurementunits
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
