name: acornassociated.lojistiks::lang.models.measurementunit.label
form: $/acornassociated/lojistiks/models/measurementunit/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\MeasurementUnit
defaultRedirect: acornassociated/lojistiks/measurementunits
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/measurementunits/update/:id
  redirectClose: acornassociated/lojistiks/measurementunits
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/measurementunits
  redirectClose: acornassociated/lojistiks/measurementunits
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
