# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acorn.location::lang.models.area.label

# Model Form Field configuration
form: $/acorn/lojistiks/models/area/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Area

# Default redirect location
defaultRedirect: acorn/lojistiks/areas

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/areas/update/:id
    redirectClose: acorn/lojistiks/areas

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/areas
    redirectClose: acorn/lojistiks/areas

# Preview page
preview:
    title: backend::lang.form.preview_title
