plugin:
    name: acorn.lojistiks::lang.plugin.name
    description: 'Lojistiks'
    author: 'Acorn'
    icon: wn-icon-calendar
    replaces: {  }
navigation:
    find-by-qrcode:
        label: acorn.lojistiks::lang.models.general.find_by_qrcode
        url: acorn/lojistiks/findbyqrcode
        icon: icon-calendar
    lojistics-actions:
        label: acorn.lojistiks::lang.plugin.actions
        url:
        icon: icon-calendar
        sideMenu:
            inventory:
                label: acorn.lojistiks::lang.plugin.inventory
                url: acorn/lojistiks/productinstances/create
                icon: icon-calendar
            transfer-inventory:
                label: acorn.lojistiks::lang.models.transfer.transfer_inventory
                url: acorn/lojistiks/transfers/create?uses-quantity=hide
                icon: icon-calendar
            transfer-quantity:
                label: acorn.lojistiks::lang.models.transfer.transfer_quantity
                url: acorn/lojistiks/transfers/create?uses-inventory=hide
                icon: icon-calendar
            transfer:
                label: acorn.lojistiks::lang.models.transfer.label
                url: acorn/lojistiks/transfers/create
                icon: icon-calendar
    lojistics-reports:
        label: acorn.lojistiks::lang.plugin.reports
        url:
        icon: icon-calendar
        sideMenu:
            stock_products:
                label: acorn.lojistiks::lang.models.stockproduct.label_plural
                url: acorn/lojistiks/stockproducts
                icon: icon-calendar
            stocks:
                label: acorn.lojistiks::lang.models.stock.label_plural
                url: acorn/lojistiks/stocks
                icon: icon-calendar
    lojistics-setup:
        label: acorn.lojistiks::lang.plugin.setup
        url:
        icon: icon-calendar
        sideMenu:
            areatypes:
                label: acorn.lojistiks::lang.models.areatype.label_plural
                url: acorn/lojistiks/areatypes
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\AreaType::menuitemCount
                code: acornlojistiks
                owner: acornlojistiks
            areas:
                label: acorn.lojistiks::lang.models.area.label_plural
                url: acorn/lojistiks/areas
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\Area::menuitemCount
            offices:
                label: acorn.lojistiks::lang.models.office.label_plural
                url: acorn/lojistiks/offices
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\Office::menuitemCount
            warehouses:
                label: acorn.lojistiks::lang.models.warehouse.label_plural
                url: acorn/lojistiks/warehouses
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\Warehouse::menuitemCount
            suppliers:
                label: acorn.lojistiks::lang.models.supplier.label_plural
                url: acorn/lojistiks/suppliers
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\Supplier::menuitemCount

            brands:
                label: acorn.lojistiks::lang.models.brand.label_plural
                url: acorn/lojistiks/brands
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\Brand::menuitemCount
            measurementunits:
                label: acorn.lojistiks::lang.models.measurementunit.label_plural
                url: acorn/lojistiks/measurementunits
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\MeasurementUnit::menuitemCount
            products:
                label: acorn.lojistiks::lang.models.product.label_plural
                url: acorn/lojistiks/products
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\Product::menuitemCount
            computerproducts:
                label: acorn.lojistiks::lang.models.computerproduct.label_plural
                url: acorn/lojistiks/computerproducts
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\ComputerProduct::menuitemCount
            electronicproducts:
                label: acorn.lojistiks::lang.models.electronicproduct.label_plural
                url: acorn/lojistiks/electronicproducts
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\ElectronicProduct::menuitemCount

            people:
                label: acorn.lojistiks::lang.models.person.label_plural
                url: acorn/lojistiks/people
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\Person::menuitemCount
            drivers:
                label: acorn.lojistiks::lang.models.driver.label_plural
                url: acorn/lojistiks/drivers
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\Driver::menuitemCount
            #employees:
                #label: acorn.lojistiks::lang.models.employee.label_plural
                #url: acorn/lojistiks/employee
                #icon: icon-calendar
                #counter: \Acorn\Lojistiks\Models\Employee::menuitemCount

            vehicletypes:
                label: acorn.lojistiks::lang.models.vehicletype.label_plural
                url: acorn/lojistiks/vehiclestype
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\VehicleType::menuitemCount
            vehicles:
                label: acorn.lojistiks::lang.models.vehicle.label_plural
                url: acorn/lojistiks/vehicles
                icon: icon-calendar
                counter: \Acorn\Lojistiks\Models\Vehicle::menuitemCount
