# Created By acorn-create-system v1.0
lojistiks_products_brand:
  label: acornassociated.lojistiks::lang.models.product.label_plural
  view:
    list: $/acornassociated/lojistiks/models/product/columns.yaml
    toolbarButtons: create|delete
    showCheckboxes: true
    recordsPerPage: 10
  manage:
    form: $/acornassociated/lojistiks/models/product/fields.yaml
    recordsPerPage: 10
