name: acornassociated.lojistiks::lang.models.warehouse.label
form: $/acornassociated/lojistiks/models/warehouse/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\Warehouse
defaultRedirect: acornassociated/lojistiks/warehouses
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/warehouses/update/:id
  redirectClose: acornassociated/lojistiks/warehouses
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/warehouses
  redirectClose: acornassociated/lojistiks/warehouses
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
