name: acorn.lojistiks::lang.models.warehouse.label
form: $/acorn/lojistiks/models/warehouse/fields.yaml
modelClass: Acorn\Lojistiks\Models\Warehouse
defaultRedirect: acorn/lojistiks/warehouses
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/warehouses/update/:id
  redirectClose: acorn/lojistiks/warehouses
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/warehouses
  redirectClose: acorn/lojistiks/warehouses
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
