name: acornassociated.lojistiks::lang.models.productcategory.label
form: $/acornassociated/lojistiks/models/productcategory/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\ProductCategory
defaultRedirect: acornassociated/lojistiks/productcategories
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/productcategories/update/:id
  redirectClose: acornassociated/lojistiks/productcategories
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/productcategories
  redirectClose: acornassociated/lojistiks/productcategories
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
