# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.transfer.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/transfer/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Transfer

# Default redirect location
defaultRedirect: acorn/lojistiks/transfer

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/transfer/update/:id
    redirectClose: acorn/lojistiks/transfer

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/transfer
    redirectClose: acorn/lojistiks/transfer

# Preview page
preview:
    title: backend::lang.form.preview_title
