# ===================================
#  Relation Behavior Config
# ===================================

productinstances:
    label: acorn.lojistiks::lang.models.general.label
    list: ~/plugins/acorn/lojistiks/models/transfer/columns.yaml
    form: ~/plugins/acorn/lojistiks/models/transfer/fields.yaml
    view:
        showSearch: true
        toolbarPartial: $/acorn/lojistiks/controllers/transfer/_transfer_productinstances_toolbar.htm
        filter: $/acorn/lojistiks/models/transfer/filters.yaml
