name: acorn.lojistiks::lang.models.electronicproduct.label
form: $/acorn/lojistiks/models/electronicproduct/fields.yaml
modelClass: Acorn\Lojistiks\Models\ElectronicProduct
defaultRedirect: acorn/lojistiks/electronicproducts
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/electronicproducts/update/:id
  redirectClose: acorn/lojistiks/electronicproducts
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/electronicproducts
  redirectClose: acorn/lojistiks/electronicproducts
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
