# id (IdField) field !canFilter
# product (ForeignIdField) field !canFilter
# server (ForeignIdField) field !canFilter
scopes:
  created_at_event:
    # created_at_event
    label: acornassociated.lojistiks::lang.models.general.created_at_event
    type: daterange
    conditions: "((select aacep.start from acornassociated_calendar_event_parts aacep where aacep.event_id = created_at_event_id order by start limit 1) between ':after' and ':before')"
    modelClass: AcornAssociated\Calendar\Models\Event
    # Relation =[Xto1]> acornassociated_calendar_events(id) (created_at)
  created_by_user:
    # created_by_user
    label: acornassociated.lojistiks::lang.models.general.created_by_user
    nameFrom: fully_qualified_name
    modelClass: AcornAssociated\User\Models\User
    # Relation =[Xto1]> acornassociated_user_users(id) (created_by)
# voltage (Field) field !canFilter
# response (Field) field !canFilter
# _qrcode (PseudoField) field !canFilter
# _actions (PseudoField) field !canFilter
