name: acornassociated.lojistiks::lang.models.electronicproduct.label
form: $/acornassociated/lojistiks/models/electronicproduct/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\ElectronicProduct
defaultRedirect: acornassociated/lojistiks/electronicproducts
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/electronicproducts/update/:id
  redirectClose: acornassociated/lojistiks/electronicproducts
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/electronicproducts
  redirectClose: acornassociated/lojistiks/electronicproducts
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
