# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.product.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/product/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Product

# Default redirect location
defaultRedirect: acorn/lojistiks/product

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/product/update/:id
    redirectClose: acorn/lojistiks/product

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/product
    redirectClose: acorn/lojistiks/product

# Preview page
preview:
    title: backend::lang.form.preview_title
