# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.lojistiks::lang.models.product.label'

# Model Form Field configuration
form: $/acornassociated/lojistiks/models/product/fields.yaml

# Model Class name
modelClass: AcornAssociated\Lojistiks\Models\Product

# Default redirect location
defaultRedirect: acornassociated/lojistiks/product

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/lojistiks/product/update/:id
    redirectClose: acornassociated/lojistiks/product

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/lojistiks/product
    redirectClose: acornassociated/lojistiks/product

# Preview page
preview:
    title: backend::lang.form.preview_title
