# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.area.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/area/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Area

# Default redirect location
defaultRedirect: acorn/lojistiks/area

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/area/update/:id
    redirectClose: acorn/lojistiks/area

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/area
    redirectClose: acorn/lojistiks/area

# Preview page
preview:
    title: backend::lang.form.preview_title
