# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.vehicle.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/vehicle/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Vehicle

# Default redirect location
defaultRedirect: acorn/lojistiks/vehicle

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/vehicle/update/:id
    redirectClose: acorn/lojistiks/vehicle

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/vehicle
    redirectClose: acorn/lojistiks/vehicle

# Preview page
preview:
    title: backend::lang.form.preview_title
