# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acorn.lojistiks::lang.models.stockproduct.label

# Model Form Field configuration
form: $/acorn/lojistiks/models/stockproduct/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\StockProduct

# Default redirect location
defaultRedirect: acorn/lojistiks/stockproducts

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/stockproducts/update/:id
    redirectClose: acorn/lojistiks/stockproducts

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/stockproducts
    redirectClose: acorn/lojistiks/stockproducts

# Preview page
preview:
    title: backend::lang.form.preview_title
