name: acornassociated.lojistiks::lang.models.transferinvoice.label
form: $/acornassociated/lojistiks/models/transferinvoice/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\TransferInvoice
defaultRedirect: acornassociated/lojistiks/transferinvoice
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/transferinvoice/update/:id
  redirectClose: acornassociated/lojistiks/transferinvoice
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/transferinvoice
  redirectClose: acornassociated/lojistiks/transferinvoice
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
