name: acorn.lojistiks::lang.models.transferinvoice.label
form: $/acorn/lojistiks/models/transferinvoice/fields.yaml
modelClass: Acorn\Lojistiks\Models\TransferInvoice
defaultRedirect: acorn/lojistiks/transferinvoice
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/transferinvoice/update/:id
  redirectClose: acorn/lojistiks/transferinvoice
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/transferinvoice
  redirectClose: acorn/lojistiks/transferinvoice
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
