name: acornassociated.lojistiks::lang.models.driver.label
form: $/acornassociated/lojistiks/models/driver/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\Driver
defaultRedirect: acornassociated/lojistiks/drivers
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/drivers/update/:id
  redirectClose: acornassociated/lojistiks/drivers
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/drivers
  redirectClose: acornassociated/lojistiks/drivers
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
