name: acorn.lojistiks::lang.models.product.label
form: $/acorn/lojistiks/models/product/fields.yaml
modelClass: Acorn\Lojistiks\Models\Product
defaultRedirect: acorn/lojistiks/products
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/products/update/:id
  redirectClose: acorn/lojistiks/products
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/products
  redirectClose: acorn/lojistiks/products
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
