# Created By acorn-create-system v1.0
lojistiks_product_instances_product:
  label: acornassociated.lojistiks::lang.models.productinstance.label_plural
  view:
    list: $/acornassociated/lojistiks/models/productinstance/columns.yaml
    toolbarButtons: create|delete
    showCheckboxes: true
    recordsPerPage: 10
  manage:
    form: $/acornassociated/lojistiks/models/productinstance/fields.yaml
    recordsPerPage: 10
lojistiks_product_products_product:
  label: acornassociated.lojistiks::lang.models.productproduct.label_plural
  view:
    list: $/acornassociated/lojistiks/models/productproduct/columns.yaml
    toolbarButtons: create|delete
    showCheckboxes: true
    recordsPerPage: 10
  manage:
    form: $/acornassociated/lojistiks/models/productproduct/fields.yaml
    recordsPerPage: 10
lojistiks_product_attributes_product:
  label: acornassociated.lojistiks::lang.models.productattribute.label_plural
  view:
    list: $/acornassociated/lojistiks/models/productattribute/columns.yaml
    toolbarButtons: create|delete
    showCheckboxes: true
    recordsPerPage: 10
  manage:
    form: $/acornassociated/lojistiks/models/productattribute/fields.yaml
    recordsPerPage: 10
lojistiks_product_products_sub_product:
  label: acornassociated.lojistiks::lang.models.productproduct.label_plural
  view:
    list: $/acornassociated/lojistiks/models/productproduct/columns.yaml
    toolbarButtons: create|delete
    showCheckboxes: true
    recordsPerPage: 10
  manage:
    form: $/acornassociated/lojistiks/models/productproduct/fields.yaml
    recordsPerPage: 10
lojistiks_products_product_category_products:
  label: acornassociated.lojistiks::lang.models.productsproductcategory.label_plural
  view:
    list: $/acornassociated/lojistiks/models/productcategory/columns.yaml
    toolbarButtons: create|delete|link|unlink
    showCheckboxes: true
    recordsPerPage: false
  manage:
    form: $/acornassociated/lojistiks/models/productcategory/fields.yaml
    recordsPerPage: false
lojistiks_product_product_category_products:
  label: acornassociated.lojistiks::lang.models.productproductcategory.label_plural
  view:
    list: $/acornassociated/lojistiks/models/productcategory/columns.yaml
    toolbarButtons: create|delete|link|unlink
    showCheckboxes: true
    recordsPerPage: false
  manage:
    form: $/acornassociated/lojistiks/models/productcategory/fields.yaml
    recordsPerPage: false
