# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.computerproduct.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/computerproduct/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\ComputerProduct

# Default redirect location
defaultRedirect: acorn/lojistiks/computerproduct

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/computerproduct/update/:id
    redirectClose: acorn/lojistiks/computerproduct

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/computerproduct
    redirectClose: acorn/lojistiks/computerproduct

# Preview page
preview:
    title: backend::lang.form.preview_title
