name: acornassociated.lojistiks::lang.models.vehicletype.label
form: $/acornassociated/lojistiks/models/vehicletype/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\VehicleType
defaultRedirect: acornassociated/lojistiks/vehicletypes
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/vehicletypes/update/:id
  redirectClose: acornassociated/lojistiks/vehicletypes
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/vehicletypes
  redirectClose: acornassociated/lojistiks/vehicletypes
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
