name: acorn.lojistiks::lang.models.vehicletype.label
form: $/acorn/lojistiks/models/vehicletype/fields.yaml
modelClass: Acorn\Lojistiks\Models\VehicleType
defaultRedirect: acorn/lojistiks/vehicletypes
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/vehicletypes/update/:id
  redirectClose: acorn/lojistiks/vehicletypes
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/vehicletypes
  redirectClose: acorn/lojistiks/vehicletypes
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
