name: acornassociated.lojistiks::lang.models.productproduct.label
form: $/acornassociated/lojistiks/models/productproduct/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\ProductProduct
defaultRedirect: acornassociated/lojistiks/productproducts
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/productproducts/update/:id
  redirectClose: acornassociated/lojistiks/productproducts
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/productproducts
  redirectClose: acornassociated/lojistiks/productproducts
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
