name: acornassociated.lojistiks::lang.models.computerproduct.label
form: $/acornassociated/lojistiks/models/computerproduct/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\ComputerProduct
defaultRedirect: acornassociated/lojistiks/computerproducts
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/computerproducts/update/:id
  redirectClose: acornassociated/lojistiks/computerproducts
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/computerproducts
  redirectClose: acornassociated/lojistiks/computerproducts
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
