name: acornassociated.lojistiks::lang.models.productsproductcategory.label
form: $/acornassociated/lojistiks/models/productsproductcategory/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\ProductsProductCategory
defaultRedirect: acornassociated/lojistiks/productsproductcategory
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/productsproductcategory/update/:id
  redirectClose: acornassociated/lojistiks/productsproductcategory
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/productsproductcategory
  redirectClose: acornassociated/lojistiks/productsproductcategory
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
