name: acorn.lojistiks::lang.models.productsproductcategory.label
form: $/acorn/lojistiks/models/productsproductcategory/fields.yaml
modelClass: Acorn\Lojistiks\Models\ProductsProductCategory
defaultRedirect: acorn/lojistiks/productsproductcategory
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/productsproductcategory/update/:id
  redirectClose: acorn/lojistiks/productsproductcategory
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/productsproductcategory
  redirectClose: acorn/lojistiks/productsproductcategory
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
