# Created By acorn-create-system v1.0
lojistiks_transfers_vehicle:
  label: acornassociated.lojistiks::lang.models.transfer.label_plural
  view:
    list: $/acornassociated/lojistiks/models/transfer/columns.yaml
    toolbarButtons: create|delete
    showCheckboxes: true
    recordsPerPage: 10
  manage:
    form: $/acornassociated/lojistiks/models/transfer/fields.yaml
    recordsPerPage: 10
lojistiks_drivers_vehicle:
  label: acornassociated.lojistiks::lang.models.driver.label_plural
  view:
    list: $/acornassociated/lojistiks/models/driver/columns.yaml
    toolbarButtons: create|delete
    showCheckboxes: true
    recordsPerPage: 10
  manage:
    form: $/acornassociated/lojistiks/models/driver/fields.yaml
    recordsPerPage: 10
