name: acorn.lojistiks::lang.models.productattribute.label
form: $/acorn/lojistiks/models/productattribute/fields.yaml
modelClass: Acorn\Lojistiks\Models\ProductAttribute
defaultRedirect: acorn/lojistiks/productattributes
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/productattributes/update/:id
  redirectClose: acorn/lojistiks/productattributes
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/productattributes
  redirectClose: acorn/lojistiks/productattributes
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
