name: acornassociated.lojistiks::lang.models.productproductcategory.label
form: $/acornassociated/lojistiks/models/productproductcategory/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\ProductProductCategory
defaultRedirect: acornassociated/lojistiks/productproductcategory
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/productproductcategory/update/:id
  redirectClose: acornassociated/lojistiks/productproductcategory
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/productproductcategory
  redirectClose: acornassociated/lojistiks/productproductcategory
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
