name: acorn.lojistiks::lang.models.productproductcategory.label
form: $/acorn/lojistiks/models/productproductcategory/fields.yaml
modelClass: Acorn\Lojistiks\Models\ProductProductCategory
defaultRedirect: acorn/lojistiks/productproductcategory
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/productproductcategory/update/:id
  redirectClose: acorn/lojistiks/productproductcategory
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/productproductcategory
  redirectClose: acorn/lojistiks/productproductcategory
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
