# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.lojistiks::lang.models.driver.label'

# Model Form Field configuration
form: $/acornassociated/lojistiks/models/driver/fields.yaml

# Model Class name
modelClass: AcornAssociated\Lojistiks\Models\Driver

# Default redirect location
defaultRedirect: acornassociated/lojistiks/driver

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/lojistiks/driver/update/:id
    redirectClose: acornassociated/lojistiks/driver

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/lojistiks/driver
    redirectClose: acornassociated/lojistiks/driver

# Preview page
preview:
    title: backend::lang.form.preview_title
