# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.driver.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/driver/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Driver

# Default redirect location
defaultRedirect: acorn/lojistiks/driver

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/driver/update/:id
    redirectClose: acorn/lojistiks/driver

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/driver
    redirectClose: acorn/lojistiks/driver

# Preview page
preview:
    title: backend::lang.form.preview_title
