# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.vehicletype.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/vehicletype/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\VehicleType

# Default redirect location
defaultRedirect: acorn/lojistiks/vehicletype

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/vehicletype/update/:id
    redirectClose: acorn/lojistiks/vehicletype

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/vehicletype
    redirectClose: acorn/lojistiks/vehicletype

# Preview page
preview:
    title: backend::lang.form.preview_title
