# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.lojistiks::lang.models.vehicletype.label'

# Model Form Field configuration
form: $/acornassociated/lojistiks/models/vehicletype/fields.yaml

# Model Class name
modelClass: AcornAssociated\Lojistiks\Models\VehicleType

# Default redirect location
defaultRedirect: acornassociated/lojistiks/vehicletype

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/lojistiks/vehicletype/update/:id
    redirectClose: acornassociated/lojistiks/vehicletype

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/lojistiks/vehicletype
    redirectClose: acornassociated/lojistiks/vehicletype

# Preview page
preview:
    title: backend::lang.form.preview_title
