# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.location.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/location/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Location

# Default redirect location
defaultRedirect: acorn/lojistiks/location

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/location/update/:id
    redirectClose: acorn/lojistiks/location

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/location
    redirectClose: acorn/lojistiks/location

# Preview page
preview:
    title: backend::lang.form.preview_title
