# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.lojistiks::lang.models.gp.label'

# Model Form Field configuration
form: $/acornassociated/lojistiks/models/gp/fields.yaml

# Model Class name
modelClass: AcornAssociated\Lojistiks\Models\GP

# Default redirect location
defaultRedirect: acornassociated/lojistiks/gps

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/lojistiks/gps/update/:id
    redirectClose: acornassociated/lojistiks/gps

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/lojistiks/gps
    redirectClose: acornassociated/lojistiks/gps

# Preview page
preview:
    title: backend::lang.form.preview_title
