# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.gp.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/gp/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\GP

# Default redirect location
defaultRedirect: acorn/lojistiks/gps

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/gps/update/:id
    redirectClose: acorn/lojistiks/gps

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/gps
    redirectClose: acorn/lojistiks/gps

# Preview page
preview:
    title: backend::lang.form.preview_title
