name: acorn.lojistiks::lang.models.supplier.label
form: $/acorn/lojistiks/models/supplier/fields.yaml
modelClass: Acorn\Lojistiks\Models\Supplier
defaultRedirect: acorn/lojistiks/suppliers
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/suppliers/update/:id
  redirectClose: acorn/lojistiks/suppliers
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/suppliers
  redirectClose: acorn/lojistiks/suppliers
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
