# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acorn.lojistiks::lang.models.supplier.label

# Model Form Field configuration
form: $/acorn/lojistiks/models/supplier/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Supplier

# Default redirect location
defaultRedirect: acorn/lojistiks/suppliers

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/suppliers/update/:id
    redirectClose: acorn/lojistiks/suppliers

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/suppliers
    redirectClose: acorn/lojistiks/suppliers

# Preview page
preview:
    title: backend::lang.form.preview_title
