name: acornassociated.lojistiks::lang.models.person.label
form: $/acornassociated/lojistiks/models/person/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\Person
defaultRedirect: acornassociated/lojistiks/people
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/people/update/:id
  redirectClose: acornassociated/lojistiks/people
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/people
  redirectClose: acornassociated/lojistiks/people
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
