# id (IdField) field !canFilter
# user[=[1to1]> acornassociated_user_users(id)] (Relation1to1) relation !canFilter
# image (Field) field !canFilter
# server (ForeignIdField) field !canFilter
scopes:
  created_at_event:
    # created_at_event
    label: acornassociated.lojistiks::lang.models.general.created_at_event
    type: daterange
    conditions: "((select aacep.start from acornassociated_calendar_event_parts aacep where aacep.event_id = created_at_event_id order by start limit 1) between ':after' and ':before')"
    modelClass: AcornAssociated\Calendar\Models\Event
    # Relation =[Xto1]> acornassociated_calendar_events(id) (created_at)
  created_by_user:
    # created_by_user
    label: acornassociated.lojistiks::lang.models.general.created_by_user
    nameFrom: fully_qualified_name
    modelClass: AcornAssociated\User\Models\User
    # Relation =[Xto1]> acornassociated_user_users(id) (created_by)
# response (Field) field !canFilter
# last_transfer_location (ForeignIdField) field !canFilter
# last_product_instance_location (ForeignIdField) field !canFilter
# description (Field) field !canFilter
# lojistiks_drivers_person (PseudoFromForeignIdField) field !canFilter
# lojistiks_employees_person (PseudoFromForeignIdField) field !canFilter
# _qrcode (PseudoField) field !canFilter
# _actions (PseudoField) field !canFilter
