# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.electronicproduct.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/electronicproduct/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\ElectronicProduct

# Default redirect location
defaultRedirect: acorn/lojistiks/electronicproduct

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/electronicproduct/update/:id
    redirectClose: acorn/lojistiks/electronicproduct

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/electronicproduct
    redirectClose: acorn/lojistiks/electronicproduct

# Preview page
preview:
    title: backend::lang.form.preview_title
