# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acorn.lojistiks::lang.models.stock.label

# Model Form Field configuration
form: $/acorn/lojistiks/models/stock/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Stock

# Default redirect location
defaultRedirect: acorn/lojistiks/stocks

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/stocks/update/:id
    redirectClose: acorn/lojistiks/stocks

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/stocks
    redirectClose: acorn/lojistiks/stocks

# Preview page
preview:
    title: backend::lang.form.preview_title
