name: acornassociated.lojistiks::lang.models.employee.label
form: $/acornassociated/lojistiks/models/employee/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\Employee
defaultRedirect: acornassociated/lojistiks/employees
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/employees/update/:id
  redirectClose: acornassociated/lojistiks/employees
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/employees
  redirectClose: acornassociated/lojistiks/employees
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
