# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: acorn.lojistiks::lang.models.location.label

# Model Form Field configuration
form: $/acorn/lojistiks/models/location/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Location

# Default redirect location
defaultRedirect: acorn/lojistiks/locations

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/locations/update/:id
    redirectClose: acorn/lojistiks/locations

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/locations
    redirectClose: acorn/lojistiks/locations

# Preview page
preview:
    title: backend::lang.form.preview_title
