# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.productinstance.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/productinstance/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\ProductInstance

# Default redirect location
defaultRedirect: acorn/lojistiks/productinstance

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/productinstance/update/:id
    redirectClose: acorn/lojistiks/productinstance

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/productinstance
    redirectClose: acorn/lojistiks/productinstance

# Preview page
preview:
    title: backend::lang.form.preview_title
