# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.lojistiks::lang.models.office.label'

# Model Form Field configuration
form: $/acornassociated/lojistiks/models/office/fields.yaml

# Model Class name
modelClass: AcornAssociated\Lojistiks\Models\Office

# Default redirect location
defaultRedirect: acornassociated/lojistiks/office

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/lojistiks/office/update/:id
    redirectClose: acornassociated/lojistiks/office

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/lojistiks/office
    redirectClose: acornassociated/lojistiks/office

# Preview page
preview:
    title: backend::lang.form.preview_title
