# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.office.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/office/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Office

# Default redirect location
defaultRedirect: acorn/lojistiks/office

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/office/update/:id
    redirectClose: acorn/lojistiks/office

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/office
    redirectClose: acorn/lojistiks/office

# Preview page
preview:
    title: backend::lang.form.preview_title
