# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.db.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/db/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\DB

# Default redirect location
defaultRedirect: acorn/lojistiks/db

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/db/update/:id
    redirectClose: acorn/lojistiks/db

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/db
    redirectClose: acorn/lojistiks/db

# Preview page
preview:
    title: backend::lang.form.preview_title
