# id (IdField) field !canFilter
# transfer (ForeignIdField) field !canFilter
# purchase (ForeignIdField) field !canFilter
# _qrcode (PseudoField) field !canFilter
# _actions (PseudoField) field !canFilter
