# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.lojistiks::lang.models.person.label'

# Model Form Field configuration
form: $/acornassociated/lojistiks/models/person/fields.yaml

# Model Class name
modelClass: AcornAssociated\Lojistiks\Models\Person

# Default redirect location
defaultRedirect: acornassociated/lojistiks/person

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/lojistiks/person/update/:id
    redirectClose: acornassociated/lojistiks/person

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/lojistiks/person
    redirectClose: acornassociated/lojistiks/person

# Preview page
preview:
    title: backend::lang.form.preview_title
