# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.warehouse.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/warehouse/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Warehouse

# Default redirect location
defaultRedirect: acorn/lojistiks/warehouse

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/warehouse/update/:id
    redirectClose: acorn/lojistiks/warehouse

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/warehouse
    redirectClose: acorn/lojistiks/warehouse

# Preview page
preview:
    title: backend::lang.form.preview_title
