name: acorn.lojistiks::lang.models.productinstance.label
form: $/acorn/lojistiks/models/productinstance/fields.yaml
modelClass: Acorn\Lojistiks\Models\ProductInstance
defaultRedirect: acorn/lojistiks/productinstances
create:
  title: backend::lang.form.create_title
  redirect: acorn/lojistiks/productinstances/update/:id
  redirectClose: acorn/lojistiks/productinstances
update:
  title: backend::lang.form.update_title
  redirect: acorn/lojistiks/productinstances
  redirectClose: acorn/lojistiks/productinstances
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
