name: acornassociated.lojistiks::lang.models.productinstance.label
form: $/acornassociated/lojistiks/models/productinstance/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\ProductInstance
defaultRedirect: acornassociated/lojistiks/productinstances
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/productinstances/update/:id
  redirectClose: acornassociated/lojistiks/productinstances
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/productinstances
  redirectClose: acornassociated/lojistiks/productinstances
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
