# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.areatype.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/areatype/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\AreaType

# Default redirect location
defaultRedirect: acorn/lojistiks/areatype

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/areatype/update/:id
    redirectClose: acorn/lojistiks/areatype

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/areatype
    redirectClose: acorn/lojistiks/areatype

# Preview page
preview:
    title: backend::lang.form.preview_title
