name: acornassociated.lojistiks::lang.models.container.label
form: $/acornassociated/lojistiks/models/container/fields.yaml
modelClass: AcornAssociated\Lojistiks\Models\Container
defaultRedirect: acornassociated/lojistiks/containers
create:
  title: backend::lang.form.create_title
  redirect: acornassociated/lojistiks/containers/update/:id
  redirectClose: acornassociated/lojistiks/containers
update:
  title: backend::lang.form.update_title
  redirect: acornassociated/lojistiks/containers
  redirectClose: acornassociated/lojistiks/containers
preview:
  title: backend::lang.form.preview_title
actionFunctions: [ ]
