# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acornassociated.lojistiks::lang.models.brand.label'

# Model Form Field configuration
form: $/acornassociated/lojistiks/models/brand/fields.yaml

# Model Class name
modelClass: AcornAssociated\Lojistiks\Models\Brand

# Default redirect location
defaultRedirect: acornassociated/lojistiks/brand

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acornassociated/lojistiks/brand/update/:id
    redirectClose: acornassociated/lojistiks/brand

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acornassociated/lojistiks/brand
    redirectClose: acornassociated/lojistiks/brand

# Preview page
preview:
    title: backend::lang.form.preview_title
