# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'acorn.lojistiks::lang.models.brand.label'

# Model Form Field configuration
form: $/acorn/lojistiks/models/brand/fields.yaml

# Model Class name
modelClass: Acorn\Lojistiks\Models\Brand

# Default redirect location
defaultRedirect: acorn/lojistiks/brand

# Create page
create:
    title: backend::lang.form.create_title
    redirect: acorn/lojistiks/brand/update/:id
    redirectClose: acorn/lojistiks/brand

# Update page
update:
    title: backend::lang.form.update_title
    redirect: acorn/lojistiks/brand
    redirectClose: acorn/lojistiks/brand

# Preview page
preview:
    title: backend::lang.form.preview_title
